# -*- coding: utf-8 -*-
"""Fund_chain_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zr-duGSNlwOre5QNPXaeloVe4VBudF6C
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="FundChain Dashboard", layout="wide")

st.title("🇪🇺 FundChain Dashboard")
st.caption("Making public funds truly public.")

# KPIs
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Projects", "142", "+4.2%")
col2.metric("Funds Allocated", "€463.8M", "+12.3%")
col3.metric("Avg AI Score", "7.4 / 10", "+0.6")
col4.metric("Pending Docs", "37", "+8")

# Data Table
st.subheader("📊 Sample Projects Overview")
data = pd.DataFrame({
    "Project": ["Athens Smart City", "Barcelona Energy Hub", "Paris Digital Infra"],
    "Country": ["Greece", "Spain", "France"],
    "Funding (€M)": [4.2, 7.8, 3.5],
    "AI Score": [8.7, 6.4, 9.2],
    "Status": ["Active", "Delayed", "Active"]
})
st.dataframe(data)

# Footer
st.markdown("---")
st.markdown("© 2025 FundChain – Making public funds truly public.")