# -*- coding: utf-8 -*-
"""Fund_chain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fJoPVzjhFziw-A5JJkz63e6FgOzm4Em
"""

FundChain Dashboard for EU
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FundChain Dashboard</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chart.js/3.9.1/chart.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
  <style>
    :root {
      --eu-blue: #1a52a1;
      --eu-yellow: #ffcc30;
      --light-blue: #cce1ff;
      --light-yellow: #fff3cc;
      --dark-gray: #333;
      --mid-gray: #666;
      --light-gray: #f5f5f5;
      --green: #28a745;
      --red: #dc3545;
      --orange: #fd7e14;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    body {
      background-color: #f8f9fa;
    }

    .header {
      background-color: var(--eu-blue);
      color: white;
      padding: 1rem 2rem;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }

    .header h1 {
      display: flex;
      align-items: center;
    }

    .logo {
      display: flex;
      align-items: center;
    }

    .logo-icon {
      width: 40px;
      height: 40px;
      border: 2px solid var(--eu-yellow);
      border-radius: 8px;
      margin-right: 12px;
      position: relative;
      background-color: var(--eu-blue);
    }

    .logo-icon::after {
      content: "";
      position: absolute;
      width: 30px;
      height: 30px;
      top: 3px;
      left: 3px;
      border: 2px solid var(--eu-yellow);
      border-radius: 4px;
    }

    .user-info {
      display: flex;
      align-items: center;
    }

    .user-info img {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      margin-left: 15px;
      border: 2px solid white;
    }

    .container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }

    .filters {
      background-color: white;
      padding: 15px;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
      margin-bottom: 20px;
      display: flex;
      flex-wrap: wrap;
      gap: 15px;
    }

    .filter-group {
      flex: 1;
      min-width: 200px;
    }

    .filter-group label {
      display: block;
      font-size: 12px;
      color: var(--mid-gray);
      margin-bottom: 5px;
    }

    .filter-group select, .filter-group input {
      width: 100%;
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 14px;
    }

    .dashboard-grid {
      display: grid;
      grid-template-columns: repeat(12, 1fr);
      grid-gap: 20px;
    }

    .overview-stats {
      grid-column: span 12;
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      grid-gap: 20px;
    }

    .stat-card {
      background-color: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
      display: flex;
      flex-direction: column;
    }

    .stat-title {
      font-size: 14px;
      color: var(--mid-gray);
      margin-bottom: 10px;
    }

    .stat-value {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .stat-change {
      font-size: 12px;
      display: flex;
      align-items: center;
    }

    .positive {
      color: var(--green);
    }

    .negative {
      color: var(--red);
    }

    .projects-list {
      grid-column: span 8;
      background-color: white;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
      overflow: hidden;
    }

    .card-header {
      padding: 15px 20px;
      border-bottom: 1px solid #eee;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .card-header h2 {
      font-size: 18px;
      font-weight: 600;
    }

    .view-all {
      color: var(--eu-blue);
      font-size: 14px;
      text-decoration: none;
    }

    .projects-table {
      width: 100%;
      border-collapse: collapse;
    }

    .projects-table th, .projects-table td {
      padding: 12px 20px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }

    .projects-table th {
      font-size: 12px;
      text-transform: uppercase;
      color: var(--mid-gray);
      font-weight: 600;
    }

    .project-name {
      display: flex;
      align-items: center;
    }

    .country-flag {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      margin-right: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 10px;
      font-weight: bold;
    }

    .greece {
      background-color: #0d5eaf;
    }

    .spain {
      background-color: #c60b1e;
    }

    .france {
      background-color: #0055a4;
    }

    .project-code {
      font-size: 12px;
      color: var(--mid-gray);
    }

    .ai-score {
      display: flex;
      align-items: center;
    }

    .score-badge {
      padding: 5px 10px;
      border-radius: 12px;
      color: white;
      font-size: 12px;
      font-weight: bold;
    }

    .score-high {
      background-color: var(--green);
    }

    .score-medium {
      background-color: var(--orange);
    }

    .score-low {
      background-color: var(--red);
    }

    .status-badge {
      padding: 5px 10px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 500;
    }

    .status-active {
      background-color: var(--light-blue);
      color: var(--eu-blue);
    }

    .status-completed {
      background-color: var(--light-yellow);
      color: #856404;
    }

    .status-delayed {
      background-color: #ffdce0;
      color: var(--red);
    }

    .blockchain-activity, .project-reports {
      grid-column: span 4;
      background-color: white;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
    }

    .blockchain-transaction {
      padding: 15px 20px;
      border-bottom: 1px solid #eee;
      display: flex;
      align-items: center;
    }

    .transaction-icon {
      width: 36px;
      height: 36px;
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-right: 12px;
    }

    .transaction-icon.send {
      background-color: var(--light-blue);
      color: var(--eu-blue);
    }

    .transaction-icon.receive {
      background-color: var(--light-yellow);
      color: #856404;
    }

    .transaction-details {
      flex-grow: 1;
      font-size: 14px;
    }

    .transaction-project {
      font-weight: 500;
    }

    .transaction-time {
      font-size: 12px;
      color: var(--mid-gray);
    }

    .transaction-amount {
      font-weight: 600;
    }

    .charts-row {
      grid-column: span 12;
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      grid-gap: 20px;
    }

    .chart-card {
      background-color: white;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
      padding: 20px;
    }

    .chart-container {
      height: 300px;
      position: relative;
    }

    .report-item {
      padding: 15px 20px;
      border-bottom: 1px solid #eee;
    }

    .report-title {
      font-weight: 500;
      margin-bottom: 5px;
      display: flex;
      justify-content: space-between;
    }

    .report-project {
      font-size: 12px;
      color: var(--mid-gray);
      margin-bottom: 8px;
    }

    .report-summary {
      font-size: 14px;
      line-height: 1.4;
      color: var(--mid-gray);
    }

    .report-date {
      font-size: 12px;
      color: var(--mid-gray);
    }

    .document-list {
      grid-column: span 12;
      background-color: white;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.05);
    }

    .documents-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      grid-gap: 15px;
      padding: 20px;
    }

    .document-card {
      border: 1px solid #eee;
      border-radius: 8px;
      overflow: hidden;
    }

    .document-icon {
      height: 120px;
      background-color: var(--light-gray);
      display: flex;
      align-items: center;
      justify-content: center;
      color: var(--mid-gray);
      font-size: 32px;
    }

    .document-info {
      padding: 12px;
    }

    .document-name {
      font-size: 14px;
      font-weight: 500;
      margin-bottom: 5px;
    }

    .document-meta {
      font-size: 12px;
      color: var(--mid-gray);
      display: flex;
      justify-content: space-between;
    }

    .eu-circle {
      position: relative;
      width: 60px;
      height: 60px;
      background: white;
      border: 2px solid var(--eu-blue);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-top: 20px;
    }

    .eu-star {
      position: absolute;
      width: 10px;
      height: 10px;
      background: var(--eu-yellow);
      clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);
    }

    /* Create 12 stars in a circle */
    .eu-star:nth-child(1) { transform: translate(20px, 0) rotate(0deg); }
    .eu-star:nth-child(2) { transform: translate(15px, -15px) rotate(30deg); }
    .eu-star:nth-child(3) { transform: translate(0, -20px) rotate(60deg); }
    .eu-star:nth-child(4) { transform: translate(-15px, -15px) rotate(90deg); }
    .eu-star:nth-child(5) { transform: translate(-20px, 0) rotate(120deg); }
    .eu-star:nth-child(6) { transform: translate(-15px, 15px) rotate(150deg); }
    .eu-star:nth-child(7) { transform: translate(0, 20px) rotate(180deg); }
    .eu-star:nth-child(8) { transform: translate(15px, 15px) rotate(210deg); }

    #eu-map-chart {
      height: 300px;
      width: 100%;
    }

    .map-tooltip {
      position: absolute;
      background: white;
      border: 1px solid #ccc;
      border-radius: 4px;
      padding: 8px;
      font-size: 12px;
      pointer-events: none;
      opacity: 0;
      transition: opacity 0.2s;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }

    .map-tooltip h3 {
      margin: 0 0 5px 0;
      font-size: 14px;
    }

    .map-tooltip p {
      margin: 0;
      color: var(--mid-gray);
    }

    .map-tooltip .funding {
      font-weight: bold;
      color: var(--eu-blue);
    }

    .map-tooltip .projects {
      margin-top: 5px;
    }

    .country {
      fill: #e0e0e0;
      stroke: white;
      stroke-width: 0.5;
      cursor: pointer;
      transition: fill 0.3s;
    }

    .country.active {
      stroke-width: 1.5;
    }

    .country.highlighted {
      stroke: var(--eu-blue);
      stroke-width: 1.5;
    }

    .country-label {
      font-size: 10px;
      font-weight: bold;
      pointer-events: none;
    }

    .legend {
      display: flex;
      justify-content: center;
      gap: 15px;
      margin-top: 10px;
      font-size: 12px;
    }

    .legend-item {
      display: flex;
      align-items: center;
    }

    .legend-color {
      width: 12px;
      height: 12px;
      border-radius: 2px;
      margin-right: 5px;
    }

    .footer {
      display: flex;
      justify-content: space-between;
      padding: 30px 0;
      margin-top: 40px;
      border-top: 1px solid #eee;
      font-size: 14px;
      color: var(--mid-gray);
    }

    @media (max-width: 1200px) {
      .overview-stats {
        grid-template-columns: repeat(2, 1fr);
      }

      .projects-list {
        grid-column: span 12;
      }

      .blockchain-activity, .project-reports {
        grid-column: span 6;
      }

      .charts-row {
        grid-template-columns: 1fr;
      }
    }

    @media (max-width: 768px) {
      .overview-stats {
        grid-template-columns: 1fr;
      }

      .blockchain-activity, .project-reports {
        grid-column: span 12;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">
      <div class="logo-icon"></div>
      <h1>FundChain</h1>
    </div>
    <div class="user-info">
      <div>
        <div>European Commission</div>
        <small>Administrator</small>
      </div>
      <img src="/api/placeholder/40/40" alt="User Avatar" />
    </div>
  </div>

  <div class="container">
    <div class="filters">
      <div class="filter-group">
        <label>Country</label>
        <select>
          <option value="">All Countries</option>
          <option value="greece">Greece</option>
          <option value="spain">Spain</option>
          <option value="france">France</option>
        </select>
      </div>
      <div class="filter-group">
        <label>Project Status</label>
        <select>
          <option value="">All Statuses</option>
          <option value="active">Active</option>
          <option value="completed">Completed</option>
          <option value="delayed">Delayed</option>
        </select>
      </div>
      <div class="filter-group">
        <label>AI Score</label>
        <select>
          <option value="">All Scores</option>
          <option value="high">High (8-10)</option>
          <option value="medium">Medium (5-7)</option>
          <option value="low">Low (0-4)</option>
        </select>
      </div>
      <div class="filter-group">
        <label>Funding Range</label>
        <select>
          <option value="">All Amounts</option>
          <option value="small">< €1M</option>
          <option value="medium">€1M - €5M</option>
          <option value="large">> €5M</option>
        </select>
      </div>
      <div class="filter-group">
        <label>Search</label>
        <input type="text" placeholder="Search projects, codes, cities...">
      </div>
    </div>

    <div class="dashboard-grid">
      <div class="overview-stats">
        <div class="stat-card">
          <div class="stat-title">Total Active Projects</div>
          <div class="stat-value">142</div>
          <div class="stat-change positive">+4.2% from previous month</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">Total Funds Allocated</div>
          <div class="stat-value">€463.8M</div>
          <div class="stat-change positive">+12.3% from previous quarter</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">Average AI Project Score</div>
          <div class="stat-value">7.4 / 10</div>
          <div class="stat-change positive">+0.6 points from previous month</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">Documents Pending Review</div>
          <div class="stat-value">37</div>
          <div class="stat-change negative">+8 from previous week</div>
        </div>
      </div>

      <div class="projects-list">
        <div class="card-header">
          <h2>Projects Overview</h2>
          <a href="#" class="view-all">View All Projects</a>
        </div>
        <table class="projects-table">
          <thead>
            <tr>
              <th>Project Name</th>
              <th>Funding</th>
              <th>AI Score</th>
              <th>Status</th>
              <th>Last Update</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <div class="project-name">
                  <div class="country-flag greece">GR</div>
                  <div>
                    <div>Athens Smart City Initiative</div>
                    <div class="project-code">GR-2023-SC097</div>
                  </div>
                </div>
              </td>
              <td>€4.2M</td>
              <td>
                <div class="ai-score">
                  <span class="score-badge score-high">8.7</span>
                </div>
              </td>
              <td><span class="status-badge status-active">Active</span></td>
              <td>2 days ago</td>
            </tr>
            <tr>
              <td>
                <div class="project-name">
                  <div class="country-flag spain">ES</div>
                  <div>
                    <div>Barcelona Renewable Energy Hub</div>
                    <div class="project-code">ES-2022-RE128</div>
                  </div>
                </div>
              </td>
              <td>€7.8M</td>
              <td>
                <div class="ai-score">
                  <span class="score-badge score-medium">6.4</span>
                </div>
              </td>
              <td><span class="status-badge status-delayed">Delayed</span></td>
              <td>5 days ago</td>
            </tr>
            <tr>
              <td>
                <div class="project-name">
                  <div class="country-flag france">FR</div>
                  <div>
                    <div>Paris Digital Infrastructure</div>
                    <div class="project-code">FR-2023-DI104</div>
                  </div>
                </div>
              </td>
              <td>€3.5M</td>
              <td>
                <div class="ai-score">
                  <span class="score-badge score-high">9.2</span>
                </div>
              </td>
              <td><span class="status-badge status-active">Active</span></td>
              <td>Today</td>
            </tr>
            <tr>
              <td>
                <div class="project-name">
                  <div class="country-flag greece">GR</div>
                  <div>
                    <div>Thessaloniki Port Modernization</div>
                    <div class="project-code">GR-2021-PM053</div>
                  </div>
                </div>
              </td>
              <td>€12.1M</td>
              <td>
                <div class="ai-score">
                  <span class="score-badge score-low">4.1</span>
                </div>
              </td>
              <td><span class="status-badge status-active">Active</span></td>
              <td>1 week ago</td>
            </tr>
            <tr>
              <td>
                <div class="project-name">
                  <div class="country-flag spain">ES</div>
                  <div>
                    <div>Valencia Healthcare Innovation</div>
                    <div class="project-code">ES-2021-HI076</div>
                  </div>
                </div>
              </td>
              <td>€2.6M</td>
              <td>
                <div class="ai-score">
                  <span class="score-badge score-high">8.9</span>
                </div>
              </td>
              <td><span class="status-badge status-completed">Completed</span></td>
              <td>3 weeks ago</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="blockchain-activity">
        <div class="card-header">
          <h2>Blockchain Transactions</h2>
          <a href="#" class="view-all">View All</a>
        </div>
        <div class="blockchain-transaction">
          <div class="transaction-icon send">€</div>
          <div class="transaction-details">
            <div class="transaction-project">Disbursement to GR-2023-SC097</div>
            <div class="transaction-time">Today, 10:23 AM</div>
          </div>
          <div class="transaction-amount">€850,000</div>
        </div>
        <div class="blockchain-transaction">
          <div class="transaction-icon receive">€</div>
          <div class="transaction-details">
            <div class="transaction-project">Receipt from ES-2022-RE128</div>
            <div class="transaction-time">Yesterday, 3:47 PM</div>
          </div>
          <div class="transaction-amount">€315,600</div>
        </div>
        <div class="blockchain-transaction">
          <div class="transaction-icon send">€</div>
          <div class="transaction-details">
            <div class="transaction-project">Disbursement to FR-2023-DI104</div>
            <div class="transaction-time">Mar 31, 2:15 PM</div>
          </div>
          <div class="transaction-amount">€750,000</div>
        </div>
        <div class="blockchain-transaction">
          <div class="transaction-icon receive">€</div>
          <div class="transaction-details">
            <div class="transaction-project">Receipt from GR-2021-PM053</div>
            <div class="transaction-time">Mar 29, 9:32 AM</div>
          </div>
          <div class="transaction-amount">€425,800</div>
        </div>
        <div class="blockchain-transaction">
          <div class="transaction-icon send">€</div>
          <div class="transaction-details">
            <div class="transaction-project">Disbursement to ES-2021-HI076</div>
            <div class="transaction-time">Mar 27, 11:05 AM</div>
          </div>
          <div class="transaction-amount">€520,000</div>
        </div>
      </div>

      <div class="project-reports">
        <div class="card-header">
          <h2>Automated Reports</h2>
          <a href="#" class="view-all">View All</a>
        </div>
        <div class="report-item">
          <div class="report-title">
            <div>Quarterly Progress Assessment</div>
            <div class="report-date">Apr 1, 2025</div>
          </div>
          <div class="report-project">Athens Smart City Initiative (GR-2023-SC097)</div>
          <div class="report-summary">Project is on schedule with 68% of milestones completed. Financial execution rate: 62% of allocated funds. All documentation in compliance with regulations.</div>
        </div>
        <div class="report-item">
          <div class="report-title">
            <div>Risk Assessment Alert</div>
            <div class="report-date">Mar 30, 2025</div>
          </div>
          <div class="report-project">Barcelona Renewable Energy Hub (ES-2022-RE128)</div>
          <div class="report-summary">Potential delay identified in solar panel installation phase. Missing 2 required permits. Recommend immediate follow-up with local authorities.</div>
        </div>
        <div class="report-item">
          <div class="report-title">
            <div>Monthly Progress Report</div>
            <div class="report-date">Mar 28, 2025</div>
          </div>
          <div class="report-project">Paris Digital Infrastructure (FR-2023-DI104)</div>
          <div class="report-summary">All project metrics above expectations. Installation phase completed 10 days ahead of schedule. Budget utilization efficient at 92% efficacy rating.</div>
        </div>
        <div class="report-item">
          <div class="report-title">
            <div>Funding Usage Analysis</div>
            <div class="report-date">Mar 25, 2025</div>
          </div>
          <div class="report-project">Thessaloniki Port Modernization (GR-2021-PM053)</div>
          <div class="report-summary">Significant budget variances detected in equipment procurement. 38% overspend in Category B. Requires immediate clarification and adjustment of financial plan.</div>
        </div>
      </div>

      <div class="charts-row">
        <div class="chart-card">
          <div class="card-header">
            <h2>Funding Distribution by Country</h2>
          </div>
          <div class="chart-container">
            <div id="eu-map-chart"></div>
            <div class="map-tooltip"></div>
            <div class="legend">
              <div class="legend-item">
                <div class="legend-color" style="background-color: #cce5ff;"></div>
                <span>0-25M €</span>
              </div>
              <div class="legend-item">
                <div class="legend-color" style="background-color: #99caff;"></div>
                <span>25-50M €</span>
              </div>
              <div class="legend-item">
                <div class="legend-color" style="background-color: #66afff;"></div>
                <span>50-75M €</span>
              </div>
              <div class="legend-item">
                <div class="legend-color" style="background-color: #3394ff;"></div>
                <span>75-100M €</span>
              </div>
              <div class="legend-item">
                <div class="legend-color" style="background-color: #0078ff;"></div>
                <span>>100M €</span>
              </div>
            </div>
          </div>
        </div>
        <div class="chart-card">
          <div class="card-header">
            <h2>AI Scores Trend</h2>
          </div>
          <div class="chart-container">
            <canvas id="aiScoreChart"></canvas>
          </div>
        </div>
      </div>

      <div class="document-list">
        <div class="card-header">
          <h2>Recent Documents</h2>
          <a href="#" class="view-all">View All Documents</a>
        </div>
        <div class="documents-grid">
          <div class="document-card">
            <div class="document-icon">PDF</div>
            <div class="document-info">
              <div class="document-name">Athens Smart City - Q1 2025 Financial